import React, { useState, useEffect, createContext, useContext, useCallback, useRef, useMemo } from 'react';
import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';
import { Search, Briefcase, Plane, Globe, PlayCircle, ChevronLeft, ChevronRight, Menu, Lightbulb, X, MessageCircle, Bookmark, CalendarClock, PlusCircle, ListChecks, ArrowLeft, Handshake, FileSignature, Newspaper, Stamp, ShieldCheck, Ticket, Siren, FolderKanban, ArrowUp, PartyPopper, Lock, Clock } from 'lucide-react';

/* --- Firebase Mock Initialization ---
let app, auth, db;
try {
  const firebaseConfig = typeof __firebase_config !== 'undefined' ? JSON.parse(__firebase_config) : {};
  app = initializeApp(firebaseConfig);
  auth = getAuth(app);
  db = getFirestore(app);
} catch (error) {
  console.error("Firebase initialization failed:", error);
}
*/

// --- i18n (Internationalization & Translations) ---
const translations = {
  pt: {
    hey: "Hey,",
    preparatorio: "Preparatório",
    days: "d", hours: "h", minutes: "m", seconds: "s",
    home_tagline: "Seu assistente preparatório de intercâmbio.",
    home_google_login: "Continuar com o Google",
    home_email_register: "Cadastrar com E-mail",
    filter_title: "Quase lá!",
    filter_subtitle: "Personalize sua jornada para uma experiência única.",
    filter_destination_label: "Seu destino dos sonhos",
    filter_destination_placeholder: "Ex: Dublin, Irlanda",
    filter_date_label: "Data de partida",
    register_button: "Salvar e Iniciar Jornada",
    timeline_title: "Linha do Tempo",
    timeline_stage_pesquisando: "Pesquisa",
    timeline_stage_negociacao: "Negociação",
    timeline_stage_intercambio_fechado: "Contrato",
    timeline_stage_visto: "Visto",
    timeline_stage_seguro: "Seguro",
    timeline_stage_aereo: "Passagem Aérea",
    timeline_stage_checkup: "Check-up Médico",
    timeline_stage_documentacao_final: "Documentos Finais",
    timeline_stage_embarque: "Embarque",
    timeline_stage_no_destino: "No Destino",
    task_where_to_start: "Por onde começar?",
    task_planning: "Planejamento Financeiro",
    task_compare_agencies: "Comparar Agências",
    task_request_quotes: "Solicitar Orçamentos",
    task_review_contract: "Revisar Contrato",
    task_make_payment: "Efetuar Pagamento",
    task_gather_visa_docs: "Reunir docs do Visto",
    task_schedule_interview: "Agendar Entrevista",
    task_get_insurance_quotes: "Cotar Seguros",
    task_issue_policy: "Emitir Apólice",
    task_search_flights: "Pesquisar Passagens",
    task_buy_ticket: "Comprar Passagem",
    task_schedule_checkup: "Agendar Consulta",
    task_get_vaccines: "Tomar Vacinas",
    task_notarize_docs: "Autenticar Documentos",
    task_organize_folder: "Organizar Pasta de Viagem",
    task_preboarding_checklist: "Checklist Pré-embarque",
    task_flight_details: "Detalhes do Voo",
    task_docs_pt2: "Documentos no Destino",
    task_accommodation: "Moradia",
    task_job: "Procurar Emprego",
    task_expenses: "Controle de Gastos",
    task_guide: "Guia Local",
    task_help: "Botão de Ajuda",
    video_tutorial_title: "Bem-vindo(a) ao OnprepX",
    video_tutorial_subtitle: "Um guia rápido para sua jornada.",
    tip_of_the_day: "Dica do Dia",
    save_tip: "Salvar Dica",
    tip_saved: "Dica salva!",
    in_construction: "Em construção...",
    terms_and_conditions: "Termos de Uso e Privacidade",
    copyright: `© ${new Date().getFullYear()} OnprepX. Todos os direitos reservados.`,
    info_menu_title: "Menu Principal",
    info_menu_desc: "Acesse todas as seções do app, configurações e seu perfil.",
    info_news_title: "Atalho para Notícias",
    info_news_desc: "Clique para rolar a tela diretamente até a seção de notícias do seu destino.",
    info_ana_title: "Ajuda da Ana",
    info_ana_desc: "Converse com nossa assistente virtual para tirar dúvidas rápidas.",
    info_tip_title: "Dica do Dia",
    info_tip_desc: "Receba uma dica valiosa para sua jornada de intercâmbio.",
    info_community_title: "Comunidade",
    info_community_desc: "Conecte-se com outros intercambistas e compartilhe experiências.",
    info_timeline_shortcut_title: "Atalho para Linha do Tempo",
    info_timeline_shortcut_desc: "Clique no ícone principal para rolar a tela diretamente até sua linha do tempo.",
    info_timeline_pesquisa_title: "Fase de Pesquisa",
    info_timeline_pesquisa_desc: "É hora de escolher o destino, a escola e planejar o orçamento. Explore suas opções!",
    info_timeline_negociacao_title: "Fase de Negociação",
    info_timeline_negociacao_desc: "Contato com agências e escolas, análise de propostas e orçamentos.",
    info_timeline_fechado_title: "Fase de Contrato",
    info_timeline_fechado_desc: "Assinatura do contrato e pagamento. Seu intercâmbio está confirmado!",
    info_timeline_visto_title: "Visto de Estudante",
    info_timeline_visto_desc: "Verifique a necessidade e os requisitos do visto para o seu destino e tipo de curso. Comece o processo o quanto antes!",
    info_timeline_seguro_title: "Seguro Saúde/Viagem",
    info_timeline_seguro_desc: "Contratar um bom seguro é obrigatório e essencial para sua segurança. Compare coberturas e preços.",
    info_timeline_aereo_title: "Passagens Aéreas",
    info_timeline_aereo_desc: "Com o curso e visto confirmados, é hora de comprar as passagens. Pesquise por promoções!",
    info_timeline_checkup_title: "Check-up Médico",
    info_timeline_checkup_desc: "Faça um check-up geral e tome as vacinas necessárias. Viajar com a saúde em dia é fundamental.",
    info_timeline_docs_title: "Documentação Final",
    info_timeline_docs_desc: "Organize todos os documentos importantes em uma pasta física e digital: passaporte, visto, carta da escola, seguro, etc.",
    info_timeline_embarque_title: "Fase de Embarque",
    info_timeline_embarque_desc: "Checklist final da mala, despedidas e detalhes do voo. A aventura está quase começando!",
    info_timeline_destino_title: "Fase No Destino",
    info_timeline_destino_desc: "Você chegou! É hora de encontrar moradia, procurar emprego e se adaptar à nova vida.",
    news_title: "OnprepX InterNews",
    notification_contract_title: "Parabéns!",
    notification_contract_desc: "Você ganhou 50% de desconto na assinatura do nosso App. Assine já e tenha acesso a conteúdos exclusivos!",
    notification_negotiation_title: "Cupom de Desconto!",
    notification_negotiation_desc: "Use o cupom ONPREPX5 em nossas agências parceiras e ganhe 5% de desconto na compra do seu intercâmbio.",
    notification_visa_title: "Cupom para Visto!",
    notification_visa_desc: "Use o cupom ONPREPX5 em nossas agências parceiras e ganhe 5% de desconto na assessoria do seu visto. Válido para vistos solicitados no Brasil.",
    notification_insurance_title: "Cupom para Seguro!",
    notification_insurance_desc: "Use o cupom ONPREPX5 em nossas agências parceiras e ganhe 5% de desconto na compra do seu Seguro Viagem.",
    notification_destination_title: "Bem-vindo(a)!",
    notification_destination_desc: "Você ganhou acesso ao nosso grupo exclusivo com dicas, modelos de CV e descontos nos cursos de nossos parceiros.",
    partners_page: "Ver Parceiros",
    guide_form_title: "Baixe seu Guia Completo!",
    guide_form_desc: "Preencha seus dados para receber o Guia Definitivo do Intercâmbio OnprepX no seu e-mail.",
    guide_form_consent: "Aceito receber e-mails com promoções e novidades.",
    guide_form_button: "Baixar Guia Agora",
    guide_form_success: "Sucesso! Seu guia foi enviado para o seu e-mail.",
    timezone_title: "Fuso Horário Global",
    timezone_local: "Horário Local",
    timezone_destination: "No seu Destino",
    timezone_search_placeholder: "Digite uma cidade...",
    timezone_search_button: "Buscar",
    timezone
